//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpgworldbuilder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public string MapImage { get; set; }
        public string MapName { get; set; }
        public int MapID { get; set; }
        public string UserID { get; set; }
        public string MapDescription { get; set; }
        public string PointsOfInterest { get; set; }
        public string UserName { get; set; }
    }
}
